#!/system/bin/sh

bindir=$(dirname "$(realpath "$0")")
execname=$(basename "$0")

if [ "$(id -u)" -ne 0 ]; then
	echo "$execname: root permission required" >&2
	exit 1
fi

exec env LD_LIBRARY_PATH=/data/adb/ssh/usr/lib "$bindir/$execname" "$@"
