#include "android-tweaks.h"
#include <stdlib.h>
#include <limits.h>
#include <stdio.h>
#include <string.h>
#include "config.h"
#ifdef WITH_OPENSSL
#include <openssl/md5.h>
#include <openssl/sha.h>
#include <openssl/des.h>
#endif

//char *sshelper_user = NULL;

//static struct passwd android_pass = { "", "", 0, 0, "", "" };

/*
 * This is a stand-in for getpwuid() on an Android system
 * running without root authority, so the usual system call
 * cannot be made. All references to getpwuid() must be
 * redirected here.
 *
 */

static char datadir_root[] = "/data/ssh/root/";
static char datadir_shell[] = "/data/ssh/shell/";
static int android_uid_tweak_isLoaded = 0;
static uid_t android_uid_tweak_uidRoot=0;
static uid_t android_uid_tweak_uidShell=2000;

static void android_uid_tweak_load(void) {
	struct passwd *pw;
	if(android_uid_tweak_isLoaded)
		return;
	android_uid_tweak_isLoaded = 1;
	pw = getpwnam("root");
	if(pw != NULL)
		android_uid_tweak_uidRoot = pw->pw_uid;
	pw = getpwnam("shell");
	if(pw != NULL)
		android_uid_tweak_uidShell = pw->pw_uid;
}

static char* getUidDir(uid_t uid) {
	if(uid == android_uid_tweak_uidRoot)
		return datadir_root;
	else if(uid == android_uid_tweak_uidShell)
		return datadir_shell;
	return NULL;
}

struct passwd* getpwuida(uid_t uid) {
	char *new_dir;
	struct passwd *pw;
	android_uid_tweak_load();
	pw = getpwuid(uid);
	if(pw != NULL && (new_dir = getUidDir(uid)) != NULL) {
		pw->pw_dir = new_dir;
	}
	if(pw) {
		pw->pw_passwd="x";
#ifdef HAVE_STRUCT_PASSWD_PW_GECOS
		pw->pw_gecos="";
#endif
	}
	return pw;
}

struct passwd *getpwnama(const char *name) {
	char *new_dir;
	struct passwd *pw;
	android_uid_tweak_load();
	pw = getpwnam(name);
	if(pw != NULL && (new_dir = getUidDir(pw->pw_uid)) != NULL) {
		pw->pw_dir = new_dir;
	}
	if(pw) {
		pw->pw_passwd="x";
#ifdef HAVE_STRUCT_PASSWD_PW_GECOS
		pw->pw_gecos="";
#endif
	}
	return pw;
}

void endgrent(void) {
}

void endpwent(void) {
}

void setpwent(void) {
}

struct passwd *getpwent(void) {
	return NULL;
}

struct spwd *getspnam(const char *name) {
	static struct spwd sp;
	static char buf[1024];
	static char namebuf[64];
	static char passbuf[256];
	FILE *fp;
	char *saveptr, *token;

	fp = fopen("/data/ssh/etc/shadow", "r");
	if (fp == NULL)
		return NULL;

	while (fgets(buf, sizeof(buf), fp) != NULL) {
		buf[strcspn(buf, "\n")] = '\0';

		token = strtok_r(buf, ":", &saveptr);
		if (token == NULL || strcmp(token, name) != 0)
			continue;

		strncpy(namebuf, token, sizeof(namebuf) - 1);
		namebuf[sizeof(namebuf) - 1] = '\0';
		sp.sp_namp = namebuf;

		token = strtok_r(NULL, ":", &saveptr);
		if (token != NULL) {
			strncpy(passbuf, token, sizeof(passbuf) - 1);
			passbuf[sizeof(passbuf) - 1] = '\0';
		} else {
			passbuf[0] = '\0';
		}
		sp.sp_pwdp = passbuf;

		sp.sp_lstchg = -1;
		sp.sp_min = -1;
		sp.sp_max = -1;
		sp.sp_warn = -1;
		sp.sp_inact = -1;
		sp.sp_expire = -1;
		sp.sp_flag = -1;

		fclose(fp);
		return &sp;
	}

	fclose(fp);
	return NULL;
}

#ifdef WITH_OPENSSL
/*
 * crypt() - password hashing for Android.
 *
 * Android bionic libc does not provide crypt(), so OpenSSH xcrypt.c
 * falls back to #define crypt DES_crypt, which only handles traditional
 * DES hashes. This custom crypt() supports $1$ (MD5-crypt) using
 * OpenSSL's MD5 API, so password authentication works with MD5 hashes
 * generated by "openssl passwd -1".
 *
 * Falls back to DES_crypt() for non-MD5 salts.
 */

static const char itoa64[] =
    "./0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

static void
to64(char *s, unsigned long v, int n)
{
	while (--n >= 0) {
		*s++ = itoa64[v & 0x3f];
		v >>= 6;
	}
}

/*
 * MD5-crypt implementation (FreeBSD/Poul-Henning Kamp algorithm).
 * Compatible with crypt(3) $1$ format used by "openssl passwd -1".
 */
static char *
crypt_md5(const char *password, const char *salt)
{
	MD5_CTX ctx, ctx1;
	unsigned char digest[MD5_DIGEST_LENGTH];
	unsigned char alt_result[MD5_DIGEST_LENGTH];
	static char result[128];
	int password_len = strlen(password);
	int salt_len, i, pl;
	const char *sp;
	char *cp;

	sp = salt + 3;
	for (salt_len = 0; salt_len < 8 && *sp && *sp != '$'; sp++)
		salt_len++;

	MD5_Init(&ctx);
	MD5_Update(&ctx, password, password_len);
	MD5_Update(&ctx, "$1$", 3);
	MD5_Update(&ctx, salt + 3, salt_len);

	MD5_Init(&ctx1);
	MD5_Update(&ctx1, password, password_len);
	MD5_Update(&ctx1, salt + 3, salt_len);
	MD5_Update(&ctx1, password, password_len);
	MD5_Final(alt_result, &ctx1);

	for (pl = password_len; pl > MD5_DIGEST_LENGTH;
	     pl -= MD5_DIGEST_LENGTH)
		MD5_Update(&ctx, alt_result, MD5_DIGEST_LENGTH);
	MD5_Update(&ctx, alt_result, pl);

	memset(alt_result, 0, MD5_DIGEST_LENGTH);

	for (i = password_len; i != 0; i >>= 1) {
		if (i & 1)
			MD5_Update(&ctx, alt_result, 1);
		else
			MD5_Update(&ctx, password, 1);
	}

	MD5_Final(digest, &ctx);

	for (i = 0; i < 1000; i++) {
		MD5_Init(&ctx);

		if (i & 1)
			MD5_Update(&ctx, password, password_len);
		else
			MD5_Update(&ctx, digest, MD5_DIGEST_LENGTH);

		if (i % 3)
			MD5_Update(&ctx, salt + 3, salt_len);

		if (i % 7)
			MD5_Update(&ctx, password, password_len);

		if (i & 1)
			MD5_Update(&ctx, digest, MD5_DIGEST_LENGTH);
		else
			MD5_Update(&ctx, password, password_len);

		MD5_Final(digest, &ctx);
	}

	cp = result;
	*cp++ = '$'; *cp++ = '1'; *cp++ = '$';
	memcpy(cp, salt + 3, salt_len);
	cp += salt_len;
	*cp++ = '$';

	{
		unsigned long v;
		v = ((unsigned long)digest[ 0] << 16) | ((unsigned long)digest[ 6] << 8) | (unsigned long)digest[12];
		to64(cp, v, 4); cp += 4;
		v = ((unsigned long)digest[ 1] << 16) | ((unsigned long)digest[ 7] << 8) | (unsigned long)digest[13];
		to64(cp, v, 4); cp += 4;
		v = ((unsigned long)digest[ 2] << 16) | ((unsigned long)digest[ 8] << 8) | (unsigned long)digest[14];
		to64(cp, v, 4); cp += 4;
		v = ((unsigned long)digest[ 3] << 16) | ((unsigned long)digest[ 9] << 8) | (unsigned long)digest[15];
		to64(cp, v, 4); cp += 4;
		v = ((unsigned long)digest[ 4] << 16) | ((unsigned long)digest[10] << 8) | (unsigned long)digest[ 5];
		to64(cp, v, 4); cp += 4;
		v = (unsigned long)digest[11];
		to64(cp, v, 2); cp += 2;
	}
	*cp = '\0';

	return result;
}

/*
 * SHA-512-crypt implementation.
 * Compatible with crypt(3) $6$ format used by "openssl passwd -6".
 */
static char *
crypt_sha512(const char *password, const char *salt)
{
	SHA512_CTX ctx, ctx1;
	unsigned char digest[SHA512_DIGEST_LENGTH];
	unsigned char alt_result[SHA512_DIGEST_LENGTH];
	static char result[128];
	size_t password_len = strlen(password);
	size_t salt_len, i, pl;
	const char *salt_start, *sp;
	unsigned char *p_bytes = NULL, *s_bytes = NULL;
	char *cp;
	unsigned int rounds = 5000;
	int rounds_custom = 0;

	sp = salt + 3;
	/* Check for rounds=NNNNN$ prefix */
	if (strncmp(sp, "rounds=", 7) == 0) {
		unsigned long parsed = strtoul(sp + 7, &cp, 10);
		if (cp != sp + 7 && *cp == '$') {
			rounds_custom = 1;
			if (parsed < 1000)
				parsed = 1000;
			if (parsed > 999999999)
				parsed = 999999999;
			rounds = (unsigned int)parsed;
			sp = cp + 1;
		}
	}
	salt_start = sp;
	for (salt_len = 0; salt_len < 16 && sp[salt_len] != '\0' &&
	    sp[salt_len] != '$'; salt_len++)
		;

	/* Digest A = password + salt + digest B repeated to password length. */
	SHA512_Init(&ctx);
	SHA512_Update(&ctx, password, password_len);
	SHA512_Update(&ctx, salt_start, salt_len);

	SHA512_Init(&ctx1);
	SHA512_Update(&ctx1, password, password_len);
	SHA512_Update(&ctx1, salt_start, salt_len);
	SHA512_Update(&ctx1, password, password_len);
	SHA512_Final(alt_result, &ctx1);

	for (pl = password_len; pl > SHA512_DIGEST_LENGTH;
	     pl -= SHA512_DIGEST_LENGTH)
		SHA512_Update(&ctx, alt_result, SHA512_DIGEST_LENGTH);
	SHA512_Update(&ctx, alt_result, pl);

	for (i = password_len; i != 0; i >>= 1) {
		if (i & 1)
			SHA512_Update(&ctx, alt_result, SHA512_DIGEST_LENGTH);
		else
			SHA512_Update(&ctx, password, password_len);
	}

	SHA512_Final(digest, &ctx);

	/* P is digest(password repeated password_len times), expanded to
	 * password_len bytes. */
	SHA512_Init(&ctx1);
	for (i = 0; i < password_len; i++)
		SHA512_Update(&ctx1, password, password_len);
	SHA512_Final(alt_result, &ctx1);
	if (password_len != 0) {
		p_bytes = malloc(password_len);
		if (p_bytes == NULL)
			return NULL;
		for (i = 0; i < password_len; i++)
			p_bytes[i] = alt_result[i % SHA512_DIGEST_LENGTH];
	}

	/* S is digest(salt repeated 16 + digest[0] times), expanded to
	 * salt_len bytes. */
	SHA512_Init(&ctx1);
	for (i = 0; i < 16U + digest[0]; i++)
		SHA512_Update(&ctx1, salt_start, salt_len);
	SHA512_Final(alt_result, &ctx1);
	if (salt_len != 0) {
		s_bytes = malloc(salt_len);
		if (s_bytes == NULL) {
			free(p_bytes);
			return NULL;
		}
		for (i = 0; i < salt_len; i++)
			s_bytes[i] = alt_result[i % SHA512_DIGEST_LENGTH];
	}

	for (i = 0; i < rounds; i++) {
		SHA512_Init(&ctx);
		if (i & 1)
			SHA512_Update(&ctx, p_bytes, password_len);
		else
			SHA512_Update(&ctx, digest, SHA512_DIGEST_LENGTH);
		if (i % 3)
			SHA512_Update(&ctx, s_bytes, salt_len);
		if (i % 7)
			SHA512_Update(&ctx, p_bytes, password_len);
		if (i & 1)
			SHA512_Update(&ctx, digest, SHA512_DIGEST_LENGTH);
		else
			SHA512_Update(&ctx, p_bytes, password_len);
		SHA512_Final(digest, &ctx);
	}
	free(p_bytes);
	free(s_bytes);
	memset(alt_result, 0, sizeof(alt_result));

	cp = result;
	*cp++ = '$'; *cp++ = '6'; *cp++ = '$';
	if (rounds_custom)
		cp += snprintf(cp, sizeof(result) - (size_t)(cp - result),
		    "rounds=%u$", rounds);
	memcpy(cp, salt_start, salt_len);
	cp += salt_len;
	*cp++ = '$';

	{
		unsigned long v;
		v = ((unsigned long)digest[ 0] << 16) | ((unsigned long)digest[21] << 8) | (unsigned long)digest[42];
		to64(cp, v, 4); cp += 4;
		v = ((unsigned long)digest[22] << 16) | ((unsigned long)digest[43] << 8) | (unsigned long)digest[ 1];
		to64(cp, v, 4); cp += 4;
		v = ((unsigned long)digest[44] << 16) | ((unsigned long)digest[ 2] << 8) | (unsigned long)digest[23];
		to64(cp, v, 4); cp += 4;
		v = ((unsigned long)digest[ 3] << 16) | ((unsigned long)digest[24] << 8) | (unsigned long)digest[45];
		to64(cp, v, 4); cp += 4;
		v = ((unsigned long)digest[25] << 16) | ((unsigned long)digest[46] << 8) | (unsigned long)digest[ 4];
		to64(cp, v, 4); cp += 4;
		v = ((unsigned long)digest[47] << 16) | ((unsigned long)digest[ 5] << 8) | (unsigned long)digest[26];
		to64(cp, v, 4); cp += 4;
		v = ((unsigned long)digest[ 6] << 16) | ((unsigned long)digest[27] << 8) | (unsigned long)digest[48];
		to64(cp, v, 4); cp += 4;
		v = ((unsigned long)digest[28] << 16) | ((unsigned long)digest[49] << 8) | (unsigned long)digest[ 7];
		to64(cp, v, 4); cp += 4;
		v = ((unsigned long)digest[50] << 16) | ((unsigned long)digest[ 8] << 8) | (unsigned long)digest[29];
		to64(cp, v, 4); cp += 4;
		v = ((unsigned long)digest[ 9] << 16) | ((unsigned long)digest[30] << 8) | (unsigned long)digest[51];
		to64(cp, v, 4); cp += 4;
		v = ((unsigned long)digest[31] << 16) | ((unsigned long)digest[52] << 8) | (unsigned long)digest[10];
		to64(cp, v, 4); cp += 4;
		v = ((unsigned long)digest[53] << 16) | ((unsigned long)digest[11] << 8) | (unsigned long)digest[32];
		to64(cp, v, 4); cp += 4;
		v = ((unsigned long)digest[12] << 16) | ((unsigned long)digest[33] << 8) | (unsigned long)digest[54];
		to64(cp, v, 4); cp += 4;
		v = ((unsigned long)digest[34] << 16) | ((unsigned long)digest[55] << 8) | (unsigned long)digest[13];
		to64(cp, v, 4); cp += 4;
		v = ((unsigned long)digest[56] << 16) | ((unsigned long)digest[14] << 8) | (unsigned long)digest[35];
		to64(cp, v, 4); cp += 4;
		v = ((unsigned long)digest[15] << 16) | ((unsigned long)digest[36] << 8) | (unsigned long)digest[57];
		to64(cp, v, 4); cp += 4;
		v = ((unsigned long)digest[37] << 16) | ((unsigned long)digest[58] << 8) | (unsigned long)digest[16];
		to64(cp, v, 4); cp += 4;
		v = ((unsigned long)digest[59] << 16) | ((unsigned long)digest[17] << 8) | (unsigned long)digest[38];
		to64(cp, v, 4); cp += 4;
		v = ((unsigned long)digest[18] << 16) | ((unsigned long)digest[39] << 8) | (unsigned long)digest[60];
		to64(cp, v, 4); cp += 4;
		v = ((unsigned long)digest[40] << 16) | ((unsigned long)digest[61] << 8) | (unsigned long)digest[19];
		to64(cp, v, 4); cp += 4;
		v = ((unsigned long)digest[62] << 16) | ((unsigned long)digest[20] << 8) | (unsigned long)digest[41];
		to64(cp, v, 4); cp += 4;
		v = (unsigned long)digest[63];
		to64(cp, v, 2); cp += 2;
	}
	*cp = '\0';

	return result;
}

char *
crypt(const char *password, const char *salt)
{
	char *result;
	if (salt == NULL || password == NULL)
		return NULL;

	if (salt[0] == '$' && salt[2] == '$') {
		if (salt[1] == '1') {
			result = crypt_md5(password, salt);
		} else if (salt[1] == '6') {
			result = crypt_sha512(password, salt);
		} else {
			goto des_fallback;
		}
		return result;
	}

des_fallback:
	return DES_crypt(password, salt);
}
#else /* !WITH_OPENSSL */
char *
crypt(const char *password, const char *salt)
{
	(void)password;
	(void)salt;
	return NULL;
}
#endif /* WITH_OPENSSL */

//
// int initgroups(const char *user, gid_t group) {
// 	return 0;
// }

//int getaddrinfo(const char *node, const char *service,
//               const struct addrinfo *hints,
//                struct addrinfo **res) {
//	return 0;
//}

// netdb:

//int getaddrinfo (const char *__restrict __name,
//			const char *__restrict __service,
//			const struct addrinfo *__restrict __req,
//			struct addrinfo **__restrict __pai) {
//	return 0;
//}

static char path_user[PATH_MAX] = ":";
static char path_suser[PATH_MAX] = ":";

const char* get_path_android(char root) {
	char *moddir;
	char *storage = root?path_suser:path_user;

	if(*storage == ':') {
		moddir = getenv("MODDIR");
		const char *formatter = root ?
		    "/system/bin:/system/xbin:/system/sbin:%s/usr/bin" :
		    "/system/bin:/system/xbin:%s/usr/bin";
		if(snprintf(storage, PATH_MAX, formatter, moddir) >= PATH_MAX) {
			storage[0] = '\0';
		}
	}
	return storage;
}
