name: Build MagiskSSH

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make wget python3 p7zip-full

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c
          add-to-path: true

      - name: Build
        run: |
          mkdir build
          cd build
          make -f ../all_arches.mk -j$(nproc) zip ANDROID_ROOT=${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: magisk-ssh
          path: build/*.zip
          if-no-files-found: error